# Generated by Django 5.2.3 on 2025-06-30 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProblemTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polygon_id",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("avg_time_taken", models.FloatField(default=30.0)),
                ("total_submissions", models.IntegerField(default=0)),
                ("problem_statement", models.TextField(blank=True, null=True)),
                ("input_format", models.TextField(blank=True, null=True)),
                ("output_format", models.TextField(blank=True, null=True)),
                ("constraints", models.TextField(blank=True, null=True)),
                ("editorial", models.TextField(blank=True, null=True)),
                (
                    "time_limit",
                    models.FloatField(
                        default=1000, help_text="Time limit in milliseconds"
                    ),
                ),
                ("problem_statement_url", models.URLField(blank=True, null=True)),
                ("additional_info", models.TextField(blank=True, null=True)),
                (
                    "memory_limit",
                    models.IntegerField(default=256, help_text="Memory limit in MB"),
                ),
                (
                    "checker_type",
                    models.CharField(
                        choices=[
                            ("ncmp", "ncmp"),
                            ("fcmp", "fcmp"),
                            ("hcmp", "hcmp"),
                            ("lcmp", "lcmp"),
                            ("nyesno", "nyesno"),
                            ("rcmp4", "rcmp4"),
                            ("rcmp6", "rcmp6"),
                            ("rcmp9", "rcmp9"),
                            ("wcmp", "wcmp"),
                            ("yesno", "yesno"),
                            ("custom", "custom"),
                        ],
                        default="ncmp",
                        max_length=10,
                    ),
                ),
                ("test_case_count", models.IntegerField(default=0)),
                ("is_locked", models.BooleanField(default=False)),
                ("genie_assist", models.BooleanField(default=False)),
                ("genie_plus", models.BooleanField(default=False)),
                ("content_video_url", models.URLField(blank=True, null=True)),
                (
                    "voice_assistant",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "extra_tags",
                    models.ManyToManyField(
                        blank=True, related_name="problems", to="problems.problemtag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProblemTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_sample", models.BooleanField(default=False)),
                ("input", models.TextField()),
                ("output", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_test_cases",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["problem", "order"],
            },
        ),
        migrations.CreateModel(
            name="SampleTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField()),
                ("output", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_test_cases",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["problem", "order"],
            },
        ),
    ]
